dist: trusty

language: perl

perl:
  - '5.26'
  - '5.14'
  - '5.10'

env:
  global:
    secure: EbGoRzfTTy/nlGPRYOEhKcYnIIrUHeM5etlqdAsMrfOkCCVJe7/QIWUG7hx1qdprIPdrKZ0jnmzBO3STz5m+TrsE/rAZjTM/MyEtwxAFEsdNlOKeozyE4Y4kwFMOqiLAFhHPtd3JhV92VMj3VSGVLkhNaaXbz1kj/aU14hOhbT4=

sudo: false

addons:
  apt:
    packages:
    - unzip

before_install:
  - git clone --branch experimental/mapper_update --depth 1 https://github.com/Ensembl/ensembl.git
  - git clone -b release-1-6-924 --depth 1 https://github.com/bioperl/bioperl-live.git

install:
  - cpanm -v --installdeps --notest .
  - perl Makefile.PL
  - make

script: "./travisci/harness.sh"

notifications:
  email:
    on_success: always
    on_failure: always
  slack:
    rooms:
      secure: crm5oSCbIpT3dQspOEhH8rUW33HGFPwRcU0VgHRFybDt09QUxnHzNNIB6b478iaignyuEZ9UOfRT5NDbb2y7AKdU4Tm4LTV6lpPPME1o+7F/hB6WT7QnajMzeVS4iWrKdlBWVyEvbHITIgUgZqfnOis1b6WWee8nETxbkAptCbE=
    on_failure: change
